name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake g++ libgtest-dev
        cd /usr/src/gtest
        sudo cmake CMakeLists.txt
        sudo make
        sudo cp lib/*.a /usr/lib
        python -m pip install pytest

    - name: Create Build Directory
      run: mkdir -p build

    - name: Configure CMake
      working-directory: build
      run: cmake ..

    - name: Build
      working-directory: build
      run: cmake --build .

    - name: Run C++ Tests
      working-directory: build
      run: ctest --output-on-failure

    - name: Run Python Integration Tests
      working-directory: build
      run: |
        python -m pytest ../tests/integration_test.py -v